### PR TITLE
Added Java 1.13 TileEntity NBT templates plus other changes.

### PR DESCRIPTION
**Pull request by StealthyExpertX**
Added tile_entity_nbt.json
Added spawner_nbt.json
Added chest_base.json
Added chest_nbt.json
Added comparator_nbt.json
Added conduit_nbt.json
Added daylight_detector_nbt.json
Added dispenser_nbt.json
Added dropper_nbt.json
Added enchanting_table_nbt.json
Added ender_chest_nbt.json
Added end_portal_nbt.json
Added hopper_nbt.json
Added shulker_box_nbt.json
Added sign_nbt.json
Added beacon_nbt.json
Added bed_nbt.json
Added brewing_stand_nbt.json
Added structure_block_nbt.json
Added skull_nbt.json
Added piston_nbt.json
Added jukebox_nbt.json
Added furnace_nbt.json
Added command_block_nbt.json
Added cauldron_nbt.json
Added banner_nbt.json
Added end_gateway_nbt.json
Added tile_tick_nbt.json

A #special note attached to this commit.
Added trapped_chest_nbt.json 

Updated chest_minecart_nbt.json

Removed the invalid "Value" tag from enderman_nbt.json
Removed the invalid "Value" tag from projectile_nbt.json

Added missing Java 1.13 cod_nbt.json
Added missing Java 1.13 salmon_nbt.json
Added missing Java 1.13 tropicalfish_nbt.json
Added missing Java 1.13 pufferfish_nbt.json

### CODE REVIEW

**Comment by StealthyExpertX** [comment]
Just finished this commit so merge it, once somebody reviews the commits please and thank you.

**Comment by Podshot** [comment]
I'll merge this once we have a basic system in-place for entities, since we want to make sure we have a solid system for them before moving on

**Comment by StealthyExpertX** [comment]
Okay, I'll start on another commit as soon as I'm able probably gonna work on 1.12 entities commit next.

**Comment by Podshot** [comment]
Closing this since we're working on a new system

**Pull request closed without merging**
