### PR TITLE
Added black stylechecking to circleci

### PR DESCRIPTION
**Pull request by freundTech**
This makes circleci fail if the code doesn't pass the black stylechecker.
Not sure if this is needed/wanted. Depends on how strictly you want the codestyle to be followed.

Also formats all files that weren't passing.

### CODE REVIEW

**Comment by naor2013** [comment]
We definitely want CI to fail if the commit/merge request doesn't follow the Black format but are you sure you're actually using the correct Black format? I don't think there should be a new line after a class declaration, right?

**Comment by freundTech** [comment]
I just ran black without any arguments for formatting and with only --check for checking and that's what it produced. Haven't used black before though.

**Comment by Podshot** [comment]
That's very odd, when I run black with our current code it doesn't format anything. I do agree though that checking style in the tests would be a good idea

**Comment by freundTech** [comment]
`black --version` tells me `black, version 18.4a2`.
`black --check src/` tells me `21 files would be reformatted, 18 files would be left unchanged.`
Running it without `--check` reformat those files.

This was ran against commit 282fb1e9bffad9a8745770e8cd654f9b60552e62

**Comment by naor2013** [comment]
I have version 18.6b4. If you can check with this newer version and resolve the merge conflicts, that would be awesome!

**Comment by freundTech** [comment]
18.6b4 throws no errors.

I can do that. But then the dependency in requirements-dev.txt should also be changed. At the moment it's requiring 18.4a2.

The latest version is 18.9b0, which only complains about minor things in 3 files (lower case hex when it should be upper case).

Should I update it to 18.6b4 or 18.9b0?

**Comment by naor2013** [comment]
The latest one probably, thanks!

**Comment by freundTech** [comment]
Done!

**Comment by naor2013** [comment]
Looks good! :D

**Comment by freundTech** [comment]
Btw: Why isn't circleci running currently? The last commit that was built is 5f9f2074088b1df99e895af543deaffbd0409d12

**Comment by naor2013** [comment]
Not sure what you mean? It checked every commit including the latest one... When you click on the "Passed" button in the README, you can see it ran on the latest commit as well

**Comment by freundTech** [comment]
Oh. Ok. For some reason it's not showing the checkmarks in the commit list for me for commits newer then the mentioned one.

**Pull request merged**
