### PR TITLE
Improved version specification

### PR DESCRIPTION
**Pull request by ezfe**
I've added the exact map format ranges for 1.12 (1.12 = 1139, 1.12.2 = 1343) and 1.13 (1.13 = 1519, 1.13.1 = 1628). I've also copied over the FML check to the 1.12 file.

### CODE REVIEW

**Comment by naor2013** [comment]
Seems like the test is failed since our 1.12 world has a version of 1497 which does not fit the limits

**Comment by naor2013** [comment]
Oh, it's because our 1.13 world uses a snapshot of 1.13 which like I said should work as well probably...
So I think it would be best to just use a min value for 1.13 which will be the first 1.13 snapshot and only set a max value for 1.12 which would be latest 1.12 release

**Comment by ezfe** [comment]
@naor2013 The reason that I didn't include the 1.13 snapshots is because the format changed a lot during that time, so I'm not actually sure they would work.

What about, instead of changing the bounds, we add a `--format=java_1_12` and a `--force` option to `world.load` so that formally unsupported versions can be forced to load.

**Comment by naor2013** [comment]
I love the idea of being able to force a load format even if it's not the correct one but we still need to include snapshots, IMO... Do you know what snapshot was the last to change the format itself? We can make it the first snapshot for now and play with it later

**Comment by naor2013** [comment]
I don't like the fact that you moved the identify call out of the load function... You should still identify there where the format parameter would be optional and there would be a force option which is also optional (ignored if no format is specified)

**Comment by naor2013** [comment]
There should hardly be any logic in the command line part since it'll need to be copied later when we'll make a UI too. We need most of the logic to be as part of the API itself so it'll be easier for us to build a UI. Plus, make sure that the tests don't fail before you commit changes please :D

**Comment by ezfe** [comment]
@naor2013 Yup, I'm working on resolving the errors now and improving the organization.

**Comment by naor2013** [comment]
If forced is true, it shouldn't check identify and error, it should just try to load like you did before

**Comment by ezfe** [comment]
@naor2013 Done

**Comment by naor2013** [comment]
So I thought the idea of choosing a format without forcing is that it will do identify on it (making it a priority format) and if it won't work, he'll run the usual code to check if another format works for it instead of erroring... Maybe your idea of doing it is better, I'm not sure, what do you think?

**Comment by ezfe** [comment]
@naor2013 I personally wouldn't expect it to revert to default identified format if the passed one doesn't match. What if the format you specify doesn't match properly for some reason and you don't notice it loaded from the default matched format.

**Comment by naor2013** [comment]
Yeah, you convinced me... The code looks really good! Sorry to keep you waiting but since it got a bit of a big change, I'll wait for Podshot to check it out and make sure everything is fine and merge it if he things everything's ok!

**Pull request merged**
