### PR TITLE
Update ru.lang

### PR DESCRIPTION
**Pull request by Max-RM**
[ru.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/7014708/ru.zip)

### CODE REVIEW

**Comment by gentlegiantJGC** [comment]
This section is duplicated. Can you work out what is correct and remove the duplicate
```
select_world.open_world_button=Открыть другой мир
select_world.open_world_dialogue=Выбрать каталог мира Майнкрафт
select_world.select_directory_failed=Не удалось открыть каталог!
select_world.recent_worlds=Недавно открытые миры

main_menu.tab_name=Главное Меню
main_menu.open_world=Открыть мир
main_menu.help=помощь

program_about.choose_from_options=Выберите из вариантов слева то, что вы хотели бы сделать.\nВы может переключаться между ними в любое время.
```

**Comment by Max-RM** [comment]
Ok

**Comment by Max-RM** [comment]
Done

**Comment by Max-RM** [comment]
[ru.lang.zip](https://github.com/Amulet-Team/Amulet-Map-Editor/files/7047302/ru.lang.zip)

**Review by gentlegiantJGC — APPROVED** [review]

**Pull request merged**
